notifications:
    email:
        - dean@airdb.com
dist: trusty
sudo: required
services:
      - docker
script:
      - echo "golintci-lint running"
      - echo ${TRAVIS_PULL_REQUEST_SLUG}
      # - docker run -v `pwd`:/go/src/github.com/${TRAVIS_REPO_SLUG}/ airdb/golint ${TRAVIS_REPO_SLUG}
      - make lint
